### ISSUE TITLE
Can´t Compile

### ISSUE THREAD

**Issue by DQ318** [kaikuehne/smes#157]
Hello, @kaikuehne .

I was Running tests on previous versions, I could almost run the application.
When creating the session at 127.0.0.18080, the SMES username suggestions screen appeared, however, loading infinitely without being allowed to proceed.
How can I do now? Does this have to do with the application not locating the POSTGRES?
With your current code, I'm stuck, I'm not leaving ...
Is there any way to disable all SUPERVISOR processes and run Backend and Frontend separately?
Thank you for listening, my dear.
Cheers!

**Comment by kaikuehne** [comment]
Yes, it will not work if it cannot access postgres.
Like I said several times already: If you don't provide logs, I'm not able to help you any further.

**Comment by kaikuehne** [comment]
Hello again.
I spent a couple of hours to make it more easier to run this project.
Please read the `README` of the project again. You need to have
basically only docker installed; then it should run.

**Comment by DQ318** [comment]
Hi, @kaikuehne.

Thank you very much for taking the time to help with the installation of the project.
I just tested and it was really FANTASTIC!
Now I'm going to do some tests and see how the code works and I'm trying to help you to increase new features going forward.
Again, thank you for donating your time to help.
Cheers!

**Comment by kaikuehne** [comment]
That's good to here, I'm closing this ticket then.

**Comment by DQ318** [comment]
@kaikuehne, yes, work rly fine in my local machine. Thanks again!

PS: I tried to run the application on a virtual machine in google cloud, I installed only ubuntu 18.04 along with docker and docker-compose and the session does not work, it loads endlessly as can be seen in the following link (http://35.188.19.244/) ... Maybe anything is missing on the server?
Everything has been compiled without apparent errors, so there is this doubt.
Thank you.

```
Status: Downloaded newer image for redis:5.0.3-alpine
Creating teste_postgres_1 ... done
Creating teste_redis_1    ... done
Creating teste_backend-celery_1 ... done
Creating teste_backend-runserver_1 ... done
Creating teste_frontend_1          ... done
**********************************************************
Please wait... will open app in a browser when it's ready.
**********************************************************
open http://localhost:8080 || xdg-open http://localhost:8080
```
