### ISSUE TITLE
Also use docker(-compose) for local development

### ISSUE THREAD

**Issue by kaikuehne** [kaikuehne/smes#9]

**Comment by DQ318** [comment]
Hi, kaikuehne. Everything okay?
Congratulations for the great work. I would like to help you develop this project, however, I could not run it locally.
I already installed everything according to your recommendations but I still can not test the application.
Any step by step to help me? I really want to help you with this project!
Thank you.

**Comment by kaikuehne** [comment]
Hi @DQ318, thanks for your comment. As stated in the README, this project was developed during my time as a student as a final project. I'm working full time now, so I will probably don't have time to devote much time into it in the future. That being said, I can try to help you to setup the project and start developing. I just looked into it and made a few changes to make it easier to get started. Please pull in the latest changes and in case it does not work, please provide the steps you did and the corresponding error message(s).

**Comment by DQ318** [comment]
Hi @kaikuehne ! Thank you very much for your support. To be honest, I could not do anything.
I tried to install and run on Ubuntu, in Windows and I could not even install the packages.
I'm just a webdesigner and all this is very new to me.
I'll read the readme file more calmly and try to install everything again and then try to run the application locally.

**Comment by DQ318** [comment]
Hello again, @kaikuehne !
So, I saw that you changed some codes and files, can I now make it work here? Hehehe
I already have everything installed but I am confused: When you say "Invoke make start" what is the correct command? Where should I put the files to test locally? = D
Again I apologize for bothering you with all this but I think I'm progressing, soon I'll be able to give you some support.
See you later =)

**Comment by kaikuehne** [comment]
Hi, you have to start a terminal and type in "make start" to start everything up.

**Comment by DQ318** [comment]
Hi!
I'm using Ubuntu 18.04 - 64 bit.
I have already installed everything (python 2 and 3, postgresql and npm).
I was able to get into the supervisor's page through the url (http://127.0.0.1:9001/) and the services are shown and everyone has the "fatal" status when I try to start.

As for the "make start" command, I get the following message on the terminal: 
**"make: Nothing to be done for 'start'."**

I already installed make too but now I'm stuck.
"sudo apt-get install ubuntu-make"

Thanks for reading and trying to help =)

**Comment by DQ318** [comment]
@kaikuehne Good Night my friend!
I've tried everything and I can not get anything to work. The most I could do was to enter the supervisor's page and see that processes do not start ...
Could you teach me a step by step to make it work locally and then online? I'm willing to pay a little money for your help, I do not want to take your time being that you've already done the code ...
Help me please

**Comment by kaikuehne** [comment]
Hi, I have fixed a couple of issues regarding the supervisor problem not starting postgres.
I cannot test this on Linux, because I have no machine, but this is the line that you need to change if you still have problems with it:

```
supervisord.conf:43:
command=postgres
```

This is just starting postgres. You maybe need to change this to `sudo postgres` or change `postgres` to something like `postgresql-server`, depending on the name of the binary of your distribution. You should find the command you need if you google on how to start postgres on Ubuntu.

You also need to make sure that the python3-version you have is not python 3.7.0, but something below (for example 3.6.6). You can use `pyenv` for this. After you have installed it, you can run `pyenv install 2.7.15`, `pyenv install 3.6.6`, and `pyenv global 2.7.15 3.6.6`. Make sure that you have configured your shell according to the pyenv docs (set PYENV_HOME etc.). After changing python versions like this, you should run `make clean` and start a new `make`.

Other than fixing problems like this from time to time, I will not be able to provide more help or invest a significant amount of time into this project; I'm sorry. Maybe you find another person that's a bit more experienced to help you with this.

By the way, there is also this nice project called http://snes.party/ which basically functions the exact same way as smes. I don't know if the code is available though.

**Comment by DQ318** [comment]
Well, I tried everything but it really did not work. This "make" command does not work on Ubuntu, even after doing all the procedures.
Which OS do you use?
I'll keep trying ... Thank you once again for all the support !!! You are amazing! = D

**Comment by kaikuehne** [comment]
I'm using macOS High Sierra. Can you post the error message you're getting?

**Comment by DQ318** [comment]
Actually I can not make anything work, even though I have everything installed, I can not even start to launch the application in the browser.
Probably this "make start" command is the root of everything ... Is something missing being installed?
Honestly I do not know what it can be, I've tried everything and I can not get out of here hahaha

**Comment by DQ318** [comment]
@kaikuehne Hi, Everything ok? I would like to know if there is any way to put your application to run directly on a web server, which contains the necessary requirements to run and test, since in my computer I could not get out of the beginning ... How do I place your application directly on a server?
Thank you

**Comment by kaikuehne** [comment]
Hi, like I said: If you don't provide the error message you're getting, unforunately I cannot help you.

**Comment by DQ318** [comment]
Hi, @kaikuehne! So, after many attempts, I managed to progress a little bit, nothing substantial ...
I was able to make, when typing make start, the compilation of the application started, however, it is not terminated due to some errors. I will show them in the images below:

![1](https://user-images.githubusercontent.com/43095999/47688454-18be5580-dbc4-11e8-81c2-823c5fb6f5b7.jpg)

![2](https://user-images.githubusercontent.com/43095999/47688459-21af2700-dbc4-11e8-951a-412336948891.jpg)

![3](https://user-images.githubusercontent.com/43095999/47688463-283d9e80-dbc4-11e8-9ab5-d0fcbd7e776b.jpg)

![4](https://user-images.githubusercontent.com/43095999/47688475-2e337f80-dbc4-11e8-8d38-24623dda07d6.jpg)

![5](https://user-images.githubusercontent.com/43095999/47688491-4905f400-dbc4-11e8-8e85-fd024297f819.jpg)

And in the supervisor some processes start and others do not:

![6](https://user-images.githubusercontent.com/43095999/47688519-84a0be00-dbc4-11e8-8af7-e01a1c7de6a1.jpg)

**Comment by DQ318** [comment]
After trying one of the previous versions, it almost worked rs ... But the same errors persist ... It seems to me that the system can not connect to redis and postgresql ...
Probably correcting these errors above will run everything correctly but I do not know how to fix

**Comment by DQ318** [comment]
Hi, @kaikuehne.

My friend, after a while away from your code, I decided to try again and .. I still could not make it work haha.
I do not know why it does not work, even in CIRCLECI the code is not passing and in my UBUNTU is with the above errors.
Any suggestion?
Cheers!
